# Generated by Django 3.2.5 on 2021-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_family', '0001_initial'),
        ('plant_pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='family',
            field=models.ManyToManyField(related_name='pictures', to='plant_family.Family'),
        ),
    ]
