# Generated by Django 3.2.5 on 2021-07-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='user',
            new_name='owner',
        ),
    ]
